name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  token: # change this
    required: true
    description: 'Github access token'
runs:
  using: 'node16'
  main: 'dist/index.js'
